ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
BOARD_TAG = nodemcuv2
USER_LIB_PATH =/home/praveenv/sambashare/Door_working_set/Example/libraries 
ARDUINO_LIBS = 

include /usr/share/arduino/Arduino.mk
